baseURL = 'https://dafengy.github.io'

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

# 网站标题
title = "大风的个人空间"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"

# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"

# 是否包括中日韩文字
hasCJKLanguage = true

# 发布目录
publishDir="docs"

# 作者配置
[author]
  name = "于峰"
  email = "yufeng.9008@gmail.com"
  link = "https://dafengy.github.io"